alertmanager:
  name:
  replicas: 1
alertmanagerConfig:
  name:
  webhookUrl:
  receivers: []
certs:
  cert:
  key:
domain:
certManager:
  namespace: cert-manager
  route53:
    region:
    hostedZoneID:
    accessKeyID:
    secretAccessKey:
