apiVersion: v1
kind: Secret
metadata:
  name: fleet-manager
type: Opaque
data:
  postgres-password: {{ "fleetmanager" | b64enc | quote }}
  auth0-client-secret: {{ .Values.fleetmanager.auth0.clientSecret | b64enc | quote }}
  oidc-client-secret: {{ .Values.fleetmanager.oidc.clientSecret | b64enc | quote }}
  MINIO_SECRET_KEY: {{ "supersecretpassword" | b64enc | quote }}
