apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: fleet-manager-grafana
  labels:
    dashboards: "grafana"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: grafana-credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: grafana-credentials
                - name: GF_USERS_DEFAULT_THEME
                  value: light
                - name: GF_PANELS_DISABLE_SANITIZE_HTML
                  value: "true"
                - name: GF_EXPLORE_ENABLED
                  value: "true"
                - name: GF_ALERTING_ENABLED
                  value: "false"
                - name: GF_UNIFIED_ALERTING_ENABLED
                  value: "false"
                - name: GF_AUTH_ANONYMOUS_ENABLED
                  value: "false"
                - name: GF_AUTH_ANONYMOUS_ORG_ROLE
                  value: Viewer
                - name: GF_AUTH_GENERIC_OAUTH_ENABLED
                  value: "true"
                - name: GF_AUTH_GENERIC_OAUTH_NAME
                  value: Streamtime Identity service
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                  value: {{ .Values.grafana.oidc.clientId }}
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                  secretKeyRef:
                    name: grafana-credentials
                    key: OIDC_CLIENT_SECRET
                    optional: false
                - name: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
                  value: "true"
                - name: GF_AUTH_GENERIC_OAUTH_SCOPES
                  value: {{ .Values.grafana.oidc.scopes }}
                - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
                  value: {{ .Values.grafana.oidc.authorizeEndpoint }}
                - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
                  value: {{ .Values.grafana.oidc.tokenEndpoint }}
                - name: GF_AUTH_GENERIC_OAUTH_API_URL
                  value: {{ .Values.grafana.oidc.userInfoEndppint }}
                - name: GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH
                  value: {{ .Values.grafana.oidc.emailClaim }}
                - name: GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC
                  value: "true"
                - name: GF_AUTH_SIGNOUT_REDIRECT_URL
                  value: {{ .Values.grafana.oidc.logoutRedirectUrl }}
                - name: GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN
                  value: "true"
                - name: GF_AUTH_DISABLE_LOGIN_FORM
                  value: "false"
                - name: GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE
                  value: "true"
                - name: GF_AUTH_PROXY_ENABLED
                  value: "true"
                - name: GF_AUTH_PROXY_HEADER_NAME
                  value: "X-Forwarded-Streamtime-User"
                - name: GF_AUTH_PROXY_HEADER_PROPERTY
                  value: "username"
                - name: GF_AUTH_PROXY_AUTO_SIGN_UP
                  value: "true"
                - name: GF_AUTH_PROXY_HEADERS
                  value: "Email:X-Forwarded-Streamtime-Email"
                - name: GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN
                  value: "false"
                - name: GF_INSTALL_PLUGINS
                  value: "https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app"
                - name: GF_SECURITY_ALLOW_EMBEDDING
                  value: "true"
                - name: GF_SECURITY_COOKIE_SAMESITE
                  value: "none"
                - name: GF_SECURITY_COOKIE_SECURE
                  value: "true"
                - name: GF_SERVER_DOMAIN
                  value: {{ include "fleetmanager.grafana.domain" . }}
                - name: GF_SERVER_ROOT_URL
                  value: https://{{ include "fleetmanager.grafana.domain" . }}/
                - name: GF_SERVER_SERVE_FROM_SUB_PATH
                  value: "false"
                - name: GF_SECURITY_DISABLE_CSRF
                  value: "true"
                - name: GF_LOG_MODE
                  value: "console"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
          securityContext:
            fsGroup: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
          volumes:
          - name: grafana-data
            persistentVolumeClaim:
              claimName: fleet-manager-grafana-pvc
  persistentVolumeClaim:
    metadata: {}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      allow_embedding: "true"
    server:
      root_url: 
