kind: Secret
apiVersion: v1
metadata:
  name: grafana-credentials
data:
  GF_SECURITY_ADMIN_PASSWORD: {{ "platformatory" | b64enc | quote }}
  GF_SECURITY_ADMIN_USER: {{ "root" | b64enc | quote }}
type: Opaque