apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: fleet-manager-grafana
  labels:
    dashboards: "grafana"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: grafana-credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: grafana-credentials
                - name: GF_USERS_DEFAULT_THEME
                  value: light
                - name: GF_PANELS_DISABLE_SANITIZE_HTML
                  value: "true"
                - name: GF_EXPLORE_ENABLED
                  value: "false"
                - name: GF_ALERTING_ENABLED
                  value: "false"
                - name: GF_UNIFIED_ALERTING_ENABLED
                  value: "false"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
          securityContext:
            fsGroup: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
          volumes:
          - name: grafana-data
            persistentVolumeClaim:
              claimName: fleet-manager-grafana-pvc
  persistentVolumeClaim:
    metadata: {}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      allow_embedding: "true"
    server:
      root_url: 
