apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: fleetmanager-mcp-authz
plugin: kong-authz-proxy
config:
  backend:
    route: "{{ .Release.Namespace }}.fleet-manager-mcp.fleet-manager-mcp.{{ include "fleetmanager.api.domain" . }}.4200"
    oidc_credentials_url_prefix: http://fleet-manager.{{ .Release.Namespace }}.svc:8000
    jwks_cache_ttl: 300
    token_source: "header"  