apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fleet-manager-mcp
  name: fleet-manager-mcp
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 4200
  selector:
    app.kubernetes.io/name: fleet-manager-mcp