apiVersion: v1
kind: Secret
metadata:
  name: temporal-worker
type: Opaque
data:
  CONFIG_S3_SECRET_KEY: {{ "supersecretpassword" | b64enc | quote }}
  TF_STATE_S3_SECRET_KEY: {{ "supersecretpassword" | b64enc | quote }}
  JWT_SECRET_KEY: {{ "kfm-256-bit-secret-key" | b64enc | quote }}