apiVersion: v1
kind: Secret
metadata:
  name: temporal-worker
type: Opaque
data:
  CONFIG_S3_SECRET_KEY: {{ "supersecretpassword" | b64enc | quote }}
  TF_STATE_S3_SECRET_KEY: {{ "supersecretpassword" | b64enc | quote }}
  OLLAMA_API_KEY: {{ "ollama" | b64enc | quote }}
  FLEETMANAGER_KUBERNETES_AWS_ACCESS_KEY: {{ .Values.fleetmanager.kubeconfig.aws.accessKey | b64enc | quote }}
  FLEETMANAGER_KUBERNETES_AWS_SECRET_KEY: {{ .Values.fleetmanager.kubeconfig.aws.secretKey | b64enc | quote }}