apiVersion: v1
kind: Secret
metadata:
  name: warpstream-s3
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.access_key | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secret_access_key | b64enc | quote }}