apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fleetmanager.org }}-api-jwt-key
  labels:
    konghq.com/credential: "jwt"
type: Opaque
data:
  kongCredType: {{ "jwt" | b64enc | quote }}
  key: {{ printf "https://%s/" .Values.fleetmanager.oidc.domain | b64enc | quote }}
  rsa_public_key: {{ .Values.fleetmanager.oidc.rsaPublicKey | b64enc | quote }}
  algorithm: {{ "RS256" | b64enc | quote }}
