apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: fleet-manager-api-{{ .Values.fleetmanager.org }}-user
  annotations:
    kubernetes.io/ingress.class: kong
username: fleet-manager-api-{{ .Values.fleetmanager.org }}-user
credentials:
  - {{ .Values.fleetmanager.org }}-api-jwt-key