{
 "title": "{{ .Release.Namespace }} Confluent Platform Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Kraft Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_server_raft_metrics_high_watermark{namespace=~\"{{ .Release.Namespace }}\", job=\"kraftcontroller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Leader",
   "type": "stat",
   "description": "The current quorum leader’s id; -1 indicates unknown.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_raft_metrics_current_leader{namespace=\"{{ .Release.Namespace }}\", job=\"kraftcontroller\"})/count(kafka_server_raft_metrics_current_leader{namespace=\"{{ .Release.Namespace }}\", job=\"kraftcontroller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=\"kraftcontroller\",namespace=\"{{ .Release.Namespace }}\"} > 0",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=\"kafka\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=\"kafka\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=\"kafka\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "stat",
   "description": "Number of partitions under min insync replicas.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{job=\"kafka\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=\"kraftcontroller\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Schema Registry Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Schemas registered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_registered_count{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Schemas deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_schemas_deleted{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  }
 ]
}