{
 "title": "{{ .Release.Namespace }} Schema Registry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Schema Registry Role",
   "type": "stat",
   "description": "The current role of this Schema Registry pod. A value of 1 indicates this pod is the primary, 0 indicates it is a secondary.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_schema_registry_master_slave_role{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Schemas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Schema Registry Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Schema registered over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(schema_type) (kafka_schema_registry_schemas_created{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"})",
     "legendFormat": "{{`{{schema_type}}`}}"
    }
   ]
  },
  {
   "title": "Schemas created",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(schema_type)(kafka_schema_registry_schemas_created{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"})",
     "legendFormat": "{{`{{schema_type}}`}}"
    }
   ]
  },
  {
   "title": "Schemas deleted",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(schema_type)(kafka_schema_registry_schemas_deleted{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"})",
     "legendFormat": "{{`{{schema_type}}`}}"
    }
   ]
  },
  {
   "title": "Schemas registered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_registered_count{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"}[5m])*100",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_used_bytes{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"})",
     "legendFormat": "Used:{{`{{pod}}`}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\",area=\"heap\"}",
     "legendFormat": "Max:{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"}[5m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jetty_metrics_connections_active{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_rate{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Requests latency 99p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_latency_99{job=\"schemaregistry\",namespace=\"{{ .Release.Namespace }}\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  }
 ]
}