{
 "title": "{{ .Release.Namespace }} Kafka Topics Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total # of Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=\"kraftcontroller\",namespace=~\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum without(pod) (rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka\",namespace=~\"{{ .Release.Namespace }}\"}[5m])))",
     "legendFormat": "{{`{{topic}}`}}"
    }
   ]
  },
  {
   "title": "Log size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(kafka_log_log_size{job=\"kafka\",namespace=\"{{ .Release.Namespace }}\"}) by (topic))",
     "legendFormat": "{{`{{topic}}`}}"
    }
   ]
  },
  {
   "title": "Total # of Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_globalpartitioncount{job=\"kraftcontroller\",namespace=~\"{{ .Release.Namespace }}\"})"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum without(pod) (rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka\",namespace=~\"{{ .Release.Namespace }}\"}[5m])))",
     "legendFormat": "{{`{{topic}}`}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum without(pod) (rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka\",namespace=~\"{{ .Release.Namespace }}\"}[5m])))",
     "legendFormat": "{{`{{topic}}`}}"
    }
   ]
  },
  {
   "title": "Produce Request per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(kafka_server_brokertopicmetrics_totalproducerequestspersec{job=\"kafka\", namespace=\"{{ .Release.Namespace }}\"}[5m])) by (topic))",
     "legendFormat": "{{`{{topic}}`}}"
    }
   ]
  },
  {
   "title": "Fetch Request per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec{job=\"kafka\", namespace=\"{{ .Release.Namespace }}\"}[5m])) by (topic))",
     "legendFormat": "{{`{{topic}}`}}"
    }
   ]
  },
  {
   "title": "Topic offsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "kafka_log_log_logstartoffset{job=\"kafka\",namespace=~\"{{ .Release.Namespace }}\"}"
    }
   ]
  },
  {
   "title": "End Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "kafka_log_log_logendoffset{job=\"kafka\",namespace=~\"{{ .Release.Namespace }}\"}"
    }
   ]
  },
  { "title": "Tiered Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Tiered size",
   "type": "timeseries",
   "description": "Total tier size",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(kafka_log_log_tiersize{job=\"kafka\",namespace=\"{{ .Release.Namespace }}\"}) by (topic))",
     "legendFormat": "{{`{{topic}}`}}"
    }
   ]
  },
  {
   "title": "Storage distribution",
   "type": "piechart",
   "description": "Total tier size",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_tiersize{job=\"kafka\",namespace=\"{{ .Release.Namespace }}\"}) by (namespace)",
     "legendFormat": "tier size"
    },
    {
     "expr": "sum(kafka_log_log_size{job=\"kafka\",namespace=\"{{ .Release.Namespace }}\"}) by (namespace)",
     "legendFormat": "disk"
    }
   ]
  }
 ]
}