{
 "title": "{{ .Release.Namespace }} CFK Logs",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Kafka Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"{{ .Release.Namespace }}\", service_name=\"kafka\"} |= ``"
    }
   ]
  },
  {
   "title": "Control Center Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{namespace=\"{{ .Release.Namespace }}\", service_name=\"controlcenter\"} |= ``"
    }
   ]
  },
  {
   "title": "Schema Registry Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"{{ .Release.Namespace }}\", service_name=\"schemaregistry\"} |= ``"
    }
   ]
  },
  {
   "title": "Kraft Controller Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{namespace=\"{{ .Release.Namespace }}\", service_name=\"kraftcontroller\"} |= ``"
    }
   ]
  }
 ]
}