apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ .Values.alertmanager.name }}
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: {{ .Values.alertmanagerConfig.name }}
