{{- if .Values.alertmanager.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager-ingress
  annotations:
    konghq.com/plugins: alertmanager-basic-auth
    external-dns.alpha.kubernetes.io/hostname: {{ printf "alerts-%s.%s" .Release.Namespace .Values.domain }}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: kong
  tls:
    - secretName: alertmanager-tls
      hosts:
        - {{ printf "alerts-%s.%s" .Release.Namespace .Values.domain }}
  rules:
    - host: {{ printf "alerts-%s.%s" .Release.Namespace .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: alertmanager-operated
                port:
                  number: 9093
            pathType: ImplementationSpecific
{{- end }}
