apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ .Values.alertmanager.name }}
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  externalUrl: https://{{ printf "%s-alerts.%s" .Release.Namespace .Values.domain }}
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: {{ .Values.alertmanagerConfig.name }}
