certs:
  kafka:
    cert:
    key:

ingressClassName:

tieredStorage:
  aws:
    accessKey:
    secretKey:

redpanda:
  image:
    tag: 
  tls:
    enabled: true
    certs:
      external:
        secretRef: 
          name: redpanda-tls
        caEnabled: false

  external:
    service:
      enabled: false
    domain: 
    addresses:
    - $PREFIX_TEMPLATE
    prefixTemplate: # "{namespace}-rp-$POD_ORDINAL"

  storage:
    persistentVolume:
      enabled: true
      size: 50Gi
    tiered:
      credentialsSecretRef:
        accessKey:
          name: redpanda-tiered-storage-creds
          key: access-key
        secretKey:
          name: redpanda-tiered-storage-creds
          key: secret-key
      config:
        cloud_storage_enabled: true
        cloud_storage_credentials_source: config_file
        cloud_storage_region: 
        cloud_storage_bucket: 
  
  statefulset:
    replicas: 3

  listeners:
    kafka:
      port: 9093
      authenticationMethod: sasl
      tls:
        enabled: false
      external:
        default:
          enabled: true
          port: 9094
          prefixTemplate: # "{namespace}-rp-$POD_ORDINAL"
          advertisedPorts:
          - 443
          tls:
            enabled: true
            cert: external
          authenticationMethod: sasl

  auth:
    sasl:
      enabled: true
      users:
      - name: admin
        password: change-me
        mechanism: SCRAM-SHA-512

  monitoring:
    enabled: true