apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redpanda-admin
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
  - secretName: tls-kafka-external
    hosts:
    - rp-admin-{{ .Release.Namespace }}.{{ .Values.redpanda.external.domain }}
  rules:
    - host: rp-admin-{{ .Release.Namespace }}.{{ .Values.redpanda.external.domain }}
      http:
        paths:
          - backend:
              service:
                name: redpanda-external
                port:
                  number: 9645
            pathType: ImplementationSpecific