apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redpanda-console
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rp-console-{{ .Release.Namespace }}.{{ .Values.redpanda.external.domain }}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
  - secretName: redpanda-tls
    hosts:
    - rp-console-{{ .Release.Namespace }}.{{ .Values.redpanda.external.domain }}
  rules:
    - host: rp-console-{{ .Release.Namespace }}.{{ .Values.redpanda.external.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-console
                port:
                  number: 8080
            pathType: ImplementationSpecific