{{ $replicas := (.Values.redpanda.statefulset.replicas | int) }}
{{- range $i, $e := until $replicas }}
{{- with $ }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $i }}
spec:
  type: ClusterIP
  ports:
  - name: admin-default
    port: 9645
    protocol: TCP
    targetPort: 9645
  - name: kafka-default
    port: 9094
    protocol: TCP
    targetPort: 9094
  - name: http-default
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: schema-default
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-{{ $i }}
...
{{- end }}
{{- end }}