apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redpanda-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/ssl-passthrough: "true"
    {{- $hostnames := list -}}
    {{- range $i := until (.Values.redpanda.statefulset.replicas | int) }}
      {{- $hostnames = append $hostnames (printf "%s-rp-%d.%s" $.Release.Namespace $i $.Values.redpanda.external.domain) -}}
    {{- end }}
    external-dns.alpha.kubernetes.io/hostname: {{ join ", " $hostnames }}
    external-dns.alpha.kubernetes.io/hostname: {{- range $i, $e := until (.Values.redpanda.statefulset.replicas | int) -}}{{ if $i }},{{ end }}{{ $.Release.Namespace }}-rp-{{ $e }}.{{ $.Values.redpanda.external.domain }}{{- end }}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: {{ .Release.Namespace }}
  tls:
    - hosts:
{{- range $i := until (.Values.redpanda.statefulset.replicas | int) }}
        - {{ $.Release.Namespace }}-rp-{{ $i }}.{{ $.Values.redpanda.external.domain }}
{{- end }}
  rules:
{{- range $i := until (.Values.redpanda.statefulset.replicas | int) }}
    - host: {{ $.Release.Namespace }}-rp-{{ $i }}.{{ $.Values.redpanda.external.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-{{ $i }}
                port:
                  number: 9094
            pathType: ImplementationSpecific
{{- end }}
