apiVersion: v1
kind: Secret
metadata:
  name: redpanda-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.certs.kafka.cert | b64enc | quote }}
  tls.key: {{ .Values.certs.kafka.key | b64enc | quote }}