apiVersion: v1
kind: Service
metadata:
  name: redpanda-external
spec:
  ports:
  - name: admin-default
    port: 9645
    protocol: TCP
    targetPort: 9645
  - name: kafka-default
    port: 9094
    protocol: TCP
    targetPort: 9094
  - name: http-default
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: schema-default
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app.kubernetes.io/component: redpanda-statefulset
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: redpanda
  type: ClusterIP