apiVersion: v1
kind: Secret
metadata:
  name: redpanda-tiered-storage-creds
type: Opaque
data:
  access-key: {{ .Values.tieredStorage.aws.accessKey | b64enc }}
  secret-key: {{ .Values.tieredStorage.aws.secretKey | b64enc }}