apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: perf-test-role-{{ .Values.benchmarkId }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: perf-test-binding-{{ .Values.benchmarkId }}
subjects:
- kind: ServiceAccount
  name: perf-test-sa-{{ .Values.benchmarkId }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: perf-test-role-{{ .Values.benchmarkId }}
