{{- $hasMonitoringCreds := or (and .Values.prometheus.username .Values.prometheus.password) (and .Values.alertmanager.username .Values.alertmanager.password) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  namespace: {{ .Values.prometheus.namespace }}
  annotations:
{{- if .Values.oauth_jwks_uri }}
    konghq.com/plugins: monitoring-jwt-auth
{{- else if $hasMonitoringCreds }}
    konghq.com/plugins: monitoring-basic-auth
{{- end }}
    konghq.com/strip-path: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.loki.hostname }}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: kong
  tls:
  - secretName: monitoring-tls
    hosts:
    - {{ .Values.loki.hostname }}
  rules:
    - host: {{ .Values.loki.hostname }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.loki.service }}
                port:
                  number: 80
{{- with .Values.loki.path }}
            path: {{ . }}
{{- end }}
            pathType: ImplementationSpecific
