apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  namespace: {{ .Values.prometheus.namespace }}
  annotations:
    konghq.com/plugins: monitoring-basic-auth
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.loki.hostname }}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: kong
  tls:
  - secretName: monitoring-tls
    hosts:
    - {{ .Values.loki.hostname }}
  rules:
    - host: {{ .Values.loki.hostname }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.loki.service }}
                port:
                  number: 80
            pathType: ImplementationSpecific