apiVersion: v1
kind: Secret
metadata:
  name: wildcard-tls
  namespace: {{ .Values.prometheus.namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.certs.cert | b64enc | quote }}
  tls.crt: {{ .Values.certs.cert | b64enc | quote }}
  tls.key: {{ .Values.certs.key | b64enc | quote }}