{{- if and (not .Values.oauth_jwks_uri) .Values.prometheus.username .Values.prometheus.password }}
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: basic-auth
  namespace: {{ .Values.prometheus.namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
username: {{ .Values.prometheus.username }}
credentials:
- basic-auth-creds
{{- end }}
