{{- if and (not .Values.oauth_jwks_uri) .Values.prometheus.username .Values.prometheus.password }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-creds
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    konghq.com/credential: basic-auth
stringData:
  kongCredType: basic-auth
  username: {{ .Values.prometheus.username }}
  password: {{ .Values.prometheus.password }}
{{- end }}
