apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fleet-manager-ui
  name: fleet-manager-ui
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: fleet-manager-ui