{
 "title": "{{ .Release.Namespace }} Warpstream Agent Overview",
 "description": "Warpstream Agent Overview",
 "tags": [ "warpstream" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Warpstream Agent Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kafka Requests / sec",
   "type": "timeseries",
   "description": "### Requests / sec\nThe rate of successful and failed Kafka requests on Warpstream write agents.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (outcome) (rate(warpstream_agent_kafka_request_latency_count{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))",
     "legendFormat": "{{`{{outcome}}`}}"
    }
   ]
  },
  {
   "title": "Kafka Requests by Type",
   "type": "timeseries",
   "description": "### Requests / sec\nThe rate of Kafka requests on Warpstream write agents by type.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kafka_key) (rate(warpstream_agent_kafka_request_latency_count{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))",
     "legendFormat": "{{`{{kafka_key}}`}}"
    }
   ]
  },
  {
   "title": "Kafka Requests Latency by Type",
   "type": "timeseries",
   "description": "### Kafka Requests Latency by Type\nAverage atency of Kafka requests on Warpstream write agents.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (kafka_key) (rate(warpstream_agent_kafka_request_latency_sum{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))\n/\nsum by (kafka_key) (rate(warpstream_agent_kafka_request_latency_count{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))\n",
     "legendFormat": "{{`{{kafka_key}}`}}"
    }
   ]
  },
  {
   "title": "Warpstream Agent Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processing of background jobs",
   "type": "timeseries",
   "description": "### Jobs / sec\nThe rate of background jobs processed by Warpstream jobs agents.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (outcome) (rate(warpstream_agent_run_and_ack_job_outcome{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))",
     "legendFormat": "{{`{{outcome}}`}}"
    }
   ]
  },
  {
   "title": "Background jobs by type",
   "type": "timeseries",
   "description": "### Background jobs by type\nRate of background jobs by type\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job_type) (rate(warpstream_agent_run_and_ack_job_outcome{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))",
     "legendFormat": "{{`{{job_type}}`}}"
    }
   ]
  },
  {
   "title": "Latency of background jobs by type",
   "type": "timeseries",
   "description": "### Latency of background jobs by type\np99 latency of background jobs by type\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, job_type) (rate(warpstream_agent_run_and_ack_job_latency_bucket{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval])))",
     "legendFormat": "{{`{{job_type}}`}}"
    }
   ]
  },
  { "title": "Warpstream Agent Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Aggregate Compressed Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "warpstream_agent_kafka_produce_compressed_bytes_sum",
     "legendFormat": "bytes produced"
    },
    {
     "expr": "warpstream_agent_kafka_fetch_compressed_bytes_sum",
     "legendFormat": "bytes consumed"
    }
   ]
  },
  {
   "title": "Aggregate Uncompressed Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "warpstream_agent_kafka_produce_uncompressed_bytes_sum",
     "legendFormat": "bytes produced"
    },
    {
     "expr": "warpstream_agent_kafka_fetch_uncompressed_bytes_sum",
     "legendFormat": "bytes consumed"
    }
   ]
  },
  {
   "title": "Per Topic Compressed Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "warpstream_agent_kafka_produce_compressed_bytes_sum",
     "legendFormat": "bytes produced - {{`{{topic}}`}}"
    },
    {
     "expr": "warpstream_agent_kafka_fetch_compressed_bytes_sum",
     "legendFormat": "bytes consumed - {{`{{topic}}`}}"
    }
   ]
  },
  {
   "title": "Per Topic Uncompressed Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "warpstream_agent_kafka_produce_uncompressed_bytes_sum",
     "legendFormat": "bytes produced - {{`{{topic}}`}}"
    },
    {
     "expr": "warpstream_agent_kafka_fetch_uncompressed_bytes_sum",
     "legendFormat": "bytes consumed - {{`{{topic}}`}}"
    }
   ]
  },
  { "title": "Flush File Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Flush File Size in Bytes - Compressed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "warpstream_agent_segment_batcher_flush_file_size_compressed_bytes_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush File Size in Bytes - Uncompressed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "warpstream_agent_segment_batcher_flush_file_size_uncompressed_bytes_count",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Lag Offsets Average by Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "avg by(consumer_group) (warpstream_consumer_group_lag{namespace=\"{{ .Release.Namespace }}\"})",
     "legendFormat": "{{`{{consumer_group}}`}}"
    }
   ]
  },
  {
   "title": "Lag Seconds Average by Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "avg by(consumer_group) (warpstream_consumer_group_estimated_lag_very_coarse_do_not_use_to_measure_e2e_seconds{namespace=\"{{ .Release.Namespace }}\"})",
     "legendFormat": "{{`{{consumer_group}}`}}"
    }
   ]
  },
  {
   "title": "Lag Offsets Average by Group and Topic-Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "avg by(consumer_group, topic, partition) (warpstream_consumer_group_lag{namespace=\"{{ .Release.Namespace }}\"})",
     "legendFormat": "{{`{{consumer_group}}`}} {{`{{topic}}`}}-{{`{{partition}}`}}"
    }
   ]
  },
  {
   "title": "Lag Seconds Average by Group and Topic-Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "avg by(consumer_group, topic, partition) (warpstream_consumer_group_estimated_lag_very_coarse_do_not_use_to_measure_e2e_seconds{namespace=\"{{ .Release.Namespace }}\"})",
     "legendFormat": "{{`{{consumer_group}}`}} {{`{{topic}}`}}-{{`{{partition}}`}}"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of files per compaction level",
   "type": "timeseries",
   "description": "### Files per level\nNumber of files per compaction level.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (compaction_level) (warpstream_files_count{namespace=~\"{{ .Release.Namespace }}\"})",
     "legendFormat": "Level{{`{{compaction_level}}`}}"
    }
   ]
  },
  {
   "title": "Bucket Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bucket operations / sec",
   "type": "timeseries",
   "description": "### Bucket operations / sec\nRate of bucket operations performed by Warpstream read agents.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(warpstream_blob_store_operation_latency_count{namespace=~\"{{ .Release.Namespace }}\", outcome=\"success\"}[$__rate_interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(warpstream_blob_store_operation_latency_count{namespace=~\"{{ .Release.Namespace }}\", outcome=\"error\"}[$__rate_interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Bucket operations by type / sec",
   "type": "timeseries",
   "description": "### Bucket operations by type / sec\nRate of bucket operations performed by Warpstream read agents by type.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(warpstream_blob_store_operation_latency_count{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{operation}}`}}"
    }
   ]
  },
  {
   "title": "Bucket operations p99 latency",
   "type": "timeseries",
   "description": "### Bucket operations p99 latency\np99 latency of bucket operations performed by Warpstream read agents.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(warpstream_blob_store_operation_latency_bucket{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))) and sum by (operation) (rate(warpstream_blob_store_operation_latency_bucket{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{operation}}`}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "description": "### Cache size\nSize of in-memory files cache\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "warpstream_agent_file_cache_server_chunk_cache_curr_size_bytes{namespace=~\"{{ .Release.Namespace }}\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Cache entries",
   "type": "timeseries",
   "description": "### Cache entries\nNumber of cache entries\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "warpstream_agent_file_cache_server_chunk_cache_num_entries{namespace=~\"{{ .Release.Namespace }}\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Cache Loads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Loads per second",
   "type": "timeseries",
   "description": "### Cache loads per second\nRate of cache loads\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (outcome) (rate(warpstream_agent_file_cache_client_fetch_local_or_remote_counter{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))",
     "legendFormat": "{{`{{outcome}}`}}"
    }
   ]
  },
  {
   "title": "Loads by source",
   "type": "timeseries",
   "description": "### Cache loads per second by source\nRate of cache loads by source.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source) (rate(warpstream_agent_file_cache_client_fetch_local_or_remote_counter{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))",
     "legendFormat": "{{`{{source}}`}}"
    }
   ]
  },
  {
   "title": "Data copied to cache per second",
   "type": "timeseries",
   "description": "### Data copied to cache per second\nRate of data copied to cache.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(warpstream_agent_file_cache_server_get_range_copy_chunk_num_bytes_copied{namespace=~\"{{ .Release.Namespace }}\"}[$__rate_interval]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "CPU / Mem usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"{{ .Release.Namespace }}\",container=~\"warpstream-agent\"}[$__rate_interval]))",
     "legendFormat": "{{`{{pod}}`}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{namespace=~\"{{ .Release.Namespace }}\",container=~\"warpstream-agent\"} / container_spec_cpu_period{namespace=~\"{{ .Release.Namespace }}\",container=~\"warpstream-agent\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"{{ .Release.Namespace }}\",container=~\"warpstream-agent\",resource=\"cpu\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=~\"{{ .Release.Namespace }}\",container=~\"warpstream-agent\"})",
     "legendFormat": "{{`{{pod}}`}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{namespace=~\"{{ .Release.Namespace }}\",container=~\"warpstream-agent\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"{{ .Release.Namespace }}\",container=~\"warpstream-agent\",resource=\"memory\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{namespace=~\"{{ .Release.Namespace }}\",pod=~\"warpstream-agent.*\"}[$__rate_interval]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Transmit bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{namespace=~\"{{ .Release.Namespace }}\",pod=~\"warpstream-agent.*\"}[$__rate_interval]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  }
 ]
}