apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-fm
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
{{- if eq .Values.tenancy "Isolated" }}
    template:
      pod:
        tolerations:
        - key: "cluster_name"
          operator: "Equal"
          value: "{{ .Release.Namespace }}"
          effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions: 
                    - key: eks.amazonaws.com/nodegroup
                      operator: In
                      values: ["{{ .Release.Namespace }}"]
{{- end }}
    version: {{ .Values.kafka.version }}
    listeners:
{{- if .Values.kafka.listeners.internal.enabled }}
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: oauth
          validIssuerUri: {{ .Values.oauth.issuer }}
          jwksEndpointUri: {{ .Values.oauth.jwksEndpoint }}
          userNameClaim: {{ .Values.oauth.subClaim }}
          maxSecondsWithoutReauthentication: 3600
          enableMetrics: true
          checkAccessTokenType: false
          disableTlsHostnameVerification: true
{{- end }}
      - name: tls
        port: 9093
        type: internal
        tls: true
{{- if .Values.kafka.listeners.external.enabled }}
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: oauth
          validIssuerUri: {{ .Values.oauth.issuer }}
          jwksEndpointUri: {{ .Values.oauth.jwksEndpoint }}
          userNameClaim: {{ .Values.oauth.subClaim }}
          maxSecondsWithoutReauthentication: 3600
          enableMetrics: true
          checkAccessTokenType: false
          disableTlsHostnameVerification: true
        configuration:
          brokerCertChainAndKey:
            secretName: tls-kafka-external
            certificate: tls.crt
            key: tls.key
          class: {{ .Release.Namespace }}
          hostTemplate: {{ .Release.Namespace }}-b{nodeId}.{{ .Values.domain }}
          bootstrap:
            host: {{ .Release.Namespace }}-bootstrap.{{ .Values.domain }}
{{- end }}
    authorization:
      type: simple
      superUsers:
        - {{ .Values.oauth.clientId }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    logging:
      type: inline
      loggers:
        log4j.rootLogger: INFO, stdout, stderr
        log4j.appender.stdout.Threshold: TRACE
        log4j.appender.stdout.Target: "System.out"
        log4j.appender.stdout.filter.filter1: "org.apache.log4j.varia.LevelRangeFilter"
        log4j.appender.stdout.filter.filter1.levelMin: TRACE
        log4j.appender.stdout.filter.filter1.levelMax: INFO
        log4j.appender.stderr: "org.apache.log4j.ConsoleAppender"
        log4j.appender.stderr.Threshold: WARN
        log4j.appender.stderr.Target: "System.err"
        log4j.appender.stderr.layout: "org.apache.log4j.PatternLayout"
        log4j.appender.stderr.layout.ConversionPattern: "[%d] %p %m (%c)%n"
  entityOperator:
    topicOperator: {}
    userOperator: {}