apiVersion: v1
kind: Secret
metadata:
  name: ca-pair-sslcerts
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.certs.ca.cert | b64enc | quote }}
  tls.key: {{ .Values.certs.ca.key | b64enc | quote }}