apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: system-admin
spec:
  principal:
    type: {{ .Values.cfk.systemAdmin.type }}
    name: {{ .Values.cfk.systemAdmin.name }}
  role: SystemAdmin