{{- if and (and .Values.certs.kafka.cert .Values.certs.kafka.key) (not .Values.certManager.route53.hostedZoneID)  }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-kafka-external
type: Opaque
data:
  ca.crt: {{ .Values.certs.kafka.cert | b64enc | quote }}
  tls.crt: {{ .Values.certs.kafka.cert | b64enc | quote }}
  tls.key: {{ .Values.certs.kafka.key | b64enc | quote }}
{{- end }}