apiVersion: v1
kind: Secret
metadata:
  name: mds-token
type: Opaque
data:
  mdsPublicKey.pem: {{ .Values.certs.mds.public | b64enc | quote }}
  mdsTokenKeyPair.pem: {{ .Values.certs.mds.keyPair | b64enc | quote }}