apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mds
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mds-{{ .Release.Namespace }}.{{ .Values.domain }}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: {{ .Release.Namespace }}
  tls:
  - secretName: tls-kafka-external
    hosts:
    - mds-{{ .Release.Namespace }}.{{ .Values.domain }}
  rules:
    - host: mds-{{ .Release.Namespace }}.{{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: mds-kafka
                port:
                  number: 9099
            pathType: ImplementationSpecific