apiVersion: v1
kind: Secret
metadata:
  name: oidccredential
type: Opaque
data:
  oidcClientSecret.txt: {{ printf "clientId=%s\nclientSecret=%s" .Values.oauth.clientId .Values.oauth.clientSecret | b64enc }}