{{- if and .Values.certManager.route53.accessKeyID .Values.certManager.route53.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials-secret
  namespace: {{ .Values.certManager.namespace }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.certManager.route53.accessKeyID | b64enc | quote }}
  aws_secret_access_key: {{ .Values.certManager.route53.secretAccessKey | b64enc | quote }}
{{- end }}