{{- if .Values.cfk.confluentPlatform.schemaRegistry.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: schema-registry
  annotations:
    external-dns.alpha.kubernetes.io/hostname: schema-{{ .Release.Namespace }}.{{ .Values.domain }}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: {{ .Release.Namespace }}
  tls:
  - secretName: tls-kafka-external
    hosts:
    - schema-{{ .Release.Namespace }}.{{ .Values.domain }}
  rules:
    - host: schema-{{ .Release.Namespace }}.{{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: schemaregistry
                port:
                  number: 8081
            pathType: ImplementationSpecific
{{- end  }}