{
 "title": "{{ .Release.Namespace }} Kube state dashboard",
 "description": "This Grafana dashboard provides a comprehensive overview of the state and performance of Kubernetes resources within your cluster, with a focus on resource counts, utilization, and availability. It covers key metrics across nodes, namespaces, pods, and containers, making it easier to monitor and troubleshoot your cluster effectively.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(kube_namespace_labels)", "legendFormat": "Namespaces" },
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", })",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels)", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels)", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info)",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_hpa_labels)", "legendFormat": "Horizontal Pod Autoscalers" },
    { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info)", "legendFormat": "Secrets" },
    { "expr": "sum(kube_networkpolicy_labels)", "legendFormat": "Network Policies" },
    {
     "expr": "count(count by (node) (kube_node_info))",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class) by (qos_class)",
     "legendFormat": "{{`{{qos_class}}`}} pods"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "Total pods" }
   ]
  },
  {
   "title": "Cluster Pod Requested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info) / sum(kube_node_status_allocatable{resource=\"pods\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory  Requested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Requested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})/ sum(kube_node_status_allocatable{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason) by (reason)",
     "legendFormat": "{{`{{qos_class}}`}}"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\"})",
     "legendFormat": "Allocatable"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "Requested" }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "Limited"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "Limited"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Not Ready - Node's",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status=\"false\"}==1",
     "legendFormat": "{{`{{node}}`}}"
    }
   ]
  },
  {
   "title": "Node Pressure",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}==1",
     "legendFormat": "{{`{{node}}`}} {{`{{condition}}`}}"
    },
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"}==1",
     "legendFormat": "{{`{{node}}`}} {{`{{condition}}`}}"
    },
    {
     "expr": "kube_node_status_condition{condition=~\"PIDPressure\",status=\"true\"}==1",
     "legendFormat": "{{`{{node}}`}} {{`{{condition}}`}}"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{container!=\"\", }[$__rate_interval])) by (namespace)",
     "legendFormat": "{{`{{namespace}}`}}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", }) by (namespace)",
     "legendFormat": "{{`{{namespace}}`}}"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas",
     "legendFormat": "{{`{{deployment}}`}}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas)"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated)"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable)"
    }
   ]
  },
  { "title": "Statefuleset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Statefulset Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready",
     "legendFormat": "{{`{{statefulset}}`}}"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)"
    }
   ]
  },
  {
   "title": "Statefulset replicas",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready/kube_statefulset_status_replicas*100",
     "legendFormat": "{{`{{statefulset}}`}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Pod's Restart in 30 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total[30m])>0",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_status_reason{reason=\"Evicted\"}==1",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running)"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated)"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true
  },
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas",
     "legendFormat": "current_{{`{{hpa}}`}}"
    },
    { "expr": "kube_hpa_spec_max_replicas", "legendFormat": "max_{{`{{hpa}}`}}" },
    { "expr": "kube_hpa_spec_min_replicas", "legendFormat": "min_{{`{{hpa}}`}}" }
   ]
  },
  {
   "title": "Total HPA Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_hpa_status_current_replicas{hpa=~\".*\"})",
     "legendFormat": "kube_hpa_status_current_replicas"
    }
   ]
  },
  {
   "title": "current==max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_max_replicas{hpa=~\".*\"}",
     "legendFormat": "{{`{{hpa}}`}}"
    }
   ]
  },
  {
   "title": "current==min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_min_replicas{hpa=~\".*\"}",
     "legendFormat": "{{`{{hpa}}`}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_job_status_succeeded)" }
   ]
  },
  {
   "title": "Job last success time from now",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 97 },
   "targets": [
    {
     "expr": "(time()-kube_job_status_completion_time)/60/60/24>1",
     "legendFormat": "{{`{{job_name}}`}}"
    }
   ]
  },
  {
   "title": "Job failed",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 97 },
   "targets": [
    { "expr": "kube_job_status_failed>1", "legendFormat": "{{`{{job_name}}`}}" }
   ]
  },
  {
   "title": "Jobs Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_job_status_active)" }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_job_status_failed)" }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "panels": [
    {
     "title": "PVC - Bound",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}==1)",
       "legendFormat": "{{`{{persistentvolumeclaim}}`}}"
      }
     ]
    },
    {
     "title": "PVC",
     "type": "table",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024",
       "legendFormat": "{{`{{persistentvolumeclaim}}`}}"
      }
     ]
    },
    {
     "title": "PVC - Not Bound",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}==1)",
       "legendFormat": "{{`{{persistentvolumeclaim}}`}}"
      }
     ]
    }
   ]
  }
 ]
}