{
 "title": "{{ .Release.Namespace }} OAuth Metrics",
 "tags": [
  "Strimzi",
  "Kafka",
  "OAuth"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "OAuth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OAuth HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(strimzi_oauth_http_requests_count{namespace=\"{{ .Release.Namespace }}\"}[$__rate_interval]) * 30",
     "legendFormat": "[{{`{{context}}`}}] {{`{{host}}`}} (Status: {{`{{status}}`}})"
    }
   ]
  },
  {
   "title": "OAuth Validation Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(strimzi_oauth_validation_requests_count{namespace=\"{{ .Release.Namespace }}\"}[$__rate_interval]) * 30",
     "legendFormat": "[{{`{{context}}`}}] {{`{{host}}`}} ({{`{{outcome}}`}})"
    }
   ]
  },
  {
   "title": "OAuth HTTP Total Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "strimzi_oauth_http_requests_count{namespace=\"{{ .Release.Namespace }}\"}",
     "legendFormat": "[{{`{{context}}`}}] {{`{{host}}`}} (Status: {{`{{status}}`}})"
    }
   ]
  },
  {
   "title": "OAuth Validation Total Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "strimzi_oauth_validation_requests_count{namespace=\"{{ .Release.Namespace }}\"}",
     "legendFormat": "[{{`{{context}}`}}] {{`{{host}}`}} ({{`{{outcome}}`}})"
    }
   ]
  },
  {
   "title": "OAuth HTTP Request Time (ms / req)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(strimzi_oauth_http_requests_totaltimems{namespace=\"{{ .Release.Namespace }}\"}[$__rate_interval]) / irate(strimzi_oauth_http_requests_count{namespace=\"{{ .Release.Namespace }}\"}[$__rate_interval])",
     "legendFormat": "[{{`{{context}}`}}] {{`{{host}}`}} (Status: {{`{{status}}`}})"
    }
   ]
  },
  {
   "title": "OAuth Validation Request Time (ms / req)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(strimzi_oauth_validation_requests_totaltimems{namespace=\"{{ .Release.Namespace }}\"}[$__rate_interval]) / irate(strimzi_oauth_validation_requests_count{namespace=\"{{ .Release.Namespace }}\"}[$__rate_interval])\n",
     "legendFormat": "[{{`{{context}}`}}] {{`{{host}}`}} ({{`{{outcome}}`}})"
    }
   ]
  }
 ]
}