{
 "title": "{{ .Release.Namespace }} Kraft Overview",
 "tags": [
  "Strimzi",
  "Kafka",
  "KRaft"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "KRaft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Kafka broker pods memory usage",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"{{ .Release.Namespace }}\",container=\"kafka\"}) by (pod)",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Aggregated Kafka broker pods CPU usage",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"{{ .Release.Namespace }}\",container=\"kafka\"}[5m])) by (pod)",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "timeseries",
   "description": "Kafka broker pods disk usage",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"{{ .Release.Namespace }}\",persistentvolumeclaim=~\"data(-[0-9]+)?-kafka-fm-.*\", persistentvolumeclaim!~\".*zookeeper(-[0-9]+)?$\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{`{{persistentvolumeclaim}}`}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Open File Descriptors",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(process_open_fds{namespace=\"{{ .Release.Namespace }}\",container=\"kafka\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"{{ .Release.Namespace }}\",strimzi_io_name=\"kafka-fm-kafka\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{namespace=\"{{ .Release.Namespace }}\",strimzi_io_name=\"kafka-fm-kafka\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{namespace=\"{{ .Release.Namespace }}\",strimzi_io_name=\"kafka-fm-kafka\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "description": "JVM thread count",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_current{namespace=\"{{ .Release.Namespace }}\",strimzi_io_name=\"kafka-fm-kafka\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Append Metadata Records Rate",
   "type": "timeseries",
   "description": "The average number of records appended per sec as the leader of the raft quorum.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_raftmetrics_append_records_rate{namespace=\"{{ .Release.Namespace }}\",strimzi_io_cluster=\"kafka-fm\"}) by (kubernetes_pod_name)",
     "legendFormat": " {{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Fetch Metadata Records Rate",
   "type": "timeseries",
   "description": "The average number of records fetched from the leader of the raft quorum.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_raftmetrics_fetch_records_rate{namespace=\"{{ .Release.Namespace }}\",strimzi_io_name=\"kafka-fm-kafka\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Metadata Records Commit Latency",
   "type": "timeseries",
   "description": "The average time in milliseconds to commit an entry in the raft log.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_server_raftmetrics_commit_latency_avg{namespace=\"{{ .Release.Namespace }}\",strimzi_io_cluster=\"kafka-fm\"}) by (kubernetes_pod_name)",
     "legendFormat": " {{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Current Raft State",
   "type": "table",
   "description": "The role of the node in KRaft",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_server_raftmetrics_current_state) by (kubernetes_pod_name, current_state)"
    }
   ]
  },
  {
   "title": "Current Quorum Leader",
   "type": "timeseries",
   "description": "The current quorum leader's id; -1 indicates unknown",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_raftmetrics_current_leader{namespace=\"{{ .Release.Namespace }}\",strimzi_io_cluster=\"kafka-fm\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Current Voted Leader",
   "type": "timeseries",
   "description": "The current voted leader's id; -1 indicates not voted for anyone",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_raftmetrics_current_vote{namespace=\"{{ .Release.Namespace }}\",strimzi_io_cluster=\"kafka-fm\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Current Quorum Epoch",
   "type": "timeseries",
   "description": "The current quorum epoch",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_raftmetrics_current_epoch{namespace=\"{{ .Release.Namespace }}\",strimzi_io_cluster=\"kafka-fm\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Metadata Topic Incoming Bytes Rate",
   "type": "timeseries",
   "description": "The number of bytes read off all sockets per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_raftchannelmetrics_incoming_byte_total{namespace=\"{{ .Release.Namespace }}\",strimzi_io_cluster=\"kafka-fm\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Metadata Topic Outgoing Bytes Rate",
   "type": "timeseries",
   "description": "The number of outgoing bytes sent to all servers per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_raftchannelmetrics_outgoing_byte_total{namespace=\"{{ .Release.Namespace }}\",strimzi_io_cluster=\"kafka-fm\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Metadata Topic Requests Rate",
   "type": "timeseries",
   "description": "The number of requests sent per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_raftchannelmetrics_request_total{namespace=\"{{ .Release.Namespace }}\",strimzi_io_cluster=\"kafka-fm\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Metadata Topic Responses Rate",
   "type": "timeseries",
   "description": "The number of responses received per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_raftchannelmetrics_response_total{namespace=\"{{ .Release.Namespace }}\",strimzi_io_cluster=\"kafka-fm\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "High Watermark",
   "type": "timeseries",
   "description": "The high watermark maintained on this member; -1 if it is unknown.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_raftmetrics_high_watermark{namespace=\"{{ .Release.Namespace }}\",strimzi_io_name=\"kafka-fm-kafka\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  },
  {
   "title": "Log End Offset",
   "type": "timeseries",
   "description": "The current raft log end offset.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_raftmetrics_log_end_offset{namespace=\"{{ .Release.Namespace }}\",strimzi_io_name=\"kafka-fm-kafka\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{`{{kubernetes_pod_name}}`}}"
    }
   ]
  }
 ]
}